runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 2

resources:
  cpu: 2
  memory_gb: 3.0
  disk_size_gb: 20

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:sochioncarry@/db?unix_socket=/cloudsql/cantonsong:us-central1:cantondb

# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: cantonsong:us-central1:cantondb
    
